data:
  root: ../data
  name: imagenette2
  resizer_image_size: 300
  image_size: 224
  num_classes: 10
  batch_size: 64
  num_workers: 8
apply_resizer_model: false
resizer:
  in_channels: 3
  out_channels: 3
  num_kernels: 16
  num_resblocks: 2
  negative_slope: 0.2
  interpolate_mode: bilinear
trainer:
  lr: 0.005
  gradient_clip_value: 0
  check_val_every_n_epoch: 10
  gpus: 1
  epochs: 250
  precision: 16
hydra:
  run:
    dir: ../outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}